title: Xingyu Chen | CV
page-top-title: Xingyu Chen
top-section-bg-text: Underraduate Student at Fudan University
home-subtitle: Xingyu Chen&ensp;|&ensp;陈星宇
copyright-text: '&copy; Xingyu Chen 2024-2026. All Rights Reserved.'
